### ISSUE TITLE
DATAMODEL - Kanban

### ISSUE THREAD

**Issue by lmag** [Evarisk/digikanban#11]
Besoin d'un Objet Kanban
![Image](https://github.com/user-attachments/assets/63ab624f-b03d-401f-b8f9-29d79ab2eddc)

-Il doit être affecté à un objet Dolibarr (Projet, taches, facture, etc...)
-Il doit avec un tag/catégorie parent qui lui appartient
-Les colonnes sont les enfants de cette catégorie parent

Les colonnes sont dans le natifs Dolibarr
![Image](https://github.com/user-attachments/assets/e41d0540-c05e-4b86-8317-785e2308db61)

Exemple de création :
![Image](https://github.com/user-attachments/assets/b149819b-80f8-4574-9950-f3dabd5e50b3)

Affichage du Kanban (Pour les personnes et/ou groupes affectés au kanban)
![Image](https://github.com/user-attachments/assets/c882e1f4-6ea4-4a3e-b2c1-57d157ee9a3b)
La gestion des droits
Lecture/écriture est réalisé par les contacts/adresse standard (la notion de groupe en V2)

**Comment by lmag** [comment]
Affichage des cards standards comme : 
![image](https://github.com/user-attachments/assets/b977a8e5-96db-4716-b08d-529b975ec9a6)
Taches
![image](https://github.com/user-attachments/assets/04cc69ba-a2d6-41a4-bca1-62ea3b6729f8)
Il faudra mettre un début de titre pour la tache et le projet

**Comment by theodaviddd** [comment]
Récap :  

Pouvoir créer un kanban sur n'importe quel type d'objet
A la création, on crée une sous catégorie avec la ref du kanban dans la catégorie "DigiKanban" de l'objet
Dans la card kanban, on peut modifier la catégorie mère si on veut.
Dans la vue kanban, les colonnes correspondent aux catégories liées
Dans les colonnes on peut ajouter des objets du type du kanban, ils ont l'apparence des cartes déjà présentes dans les vues kanban natives dolibarr
