### ISSUE TITLE
IHM-DigiKanban 1.0.0 premier design

### ISSUE THREAD

**Issue by lmag** [Evarisk/digikanban#26]
![image](https://github.com/user-attachments/assets/47155318-bc98-4702-8645-f6d7b249fbb8)

**Comment by eoxia-amandine** [comment]
Proposition de mockup V1 :
![list-kanban](https://github.com/user-attachments/assets/81a7c171-ef3d-4668-ae60-47406fe2e1c9)

Avec indications : 
![list-kanban-indications](https://github.com/user-attachments/assets/9ac5da8c-cf22-4a88-b2a8-a41ae15ab466)

Aperçu avec un fond : 
![list-kanban-fond](https://github.com/user-attachments/assets/1a02da28-a609-4887-990f-534ad5b9f1c8)

Menu option en popup : 
![list-kanban-option](https://github.com/user-attachments/assets/20aa96a1-c5eb-46b0-9e43-47035bcf243f)
